# Generated by Django 4.1.1 on 2022-11-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_article_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='NytArticle',
        ),
    ]
