# Generated by Django 4.1.1 on 2022-11-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_financialarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialarticle',
            name='url',
            field=models.URLField(default='test'),
            preserve_default=False,
        ),
    ]
