# Generated by Django 4.1.1 on 2022-11-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_financialarticle_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialarticle',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='financialarticle',
            name='tickers',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='financialarticle',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='financialarticle',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
